version: '2'
services:
    jhipster-elasticsearch:
        image: aayushjain/jhipster-elasticsearch:latest
        stdin_open: true
        tty: true
        ports:
            - "9200:9200"
    #        environment:
    #            - http.host=0.0.0.0
    #            - transport.host=127.0.0.1
        # Uncomment this section to have elasticsearch data loaded from a volume
        volumes:
           - jhipster-elasticsearch-vol:/usr/share/elasticsearch/data
        labels:
            io.rancher.container.pull_image: always

    jhipster-logstash:
        image: aayushjain/jhipster-logstash:latest
        stdin_open: true
        tty: true
        environment:
            - INPUT_UDP_PORT=5000
            - ELASTICSEARCH_HOST=jhipster-elasticsearch
            - ELASTICSEARCH_PORT=9200
        command: logstash -f /usr/share/logstash/pipeline/logstash.conf
        ports:
            - "5000:5000/udp"
        depends_on:
            - jhipster-elasticsearch
        labels:
            io.rancher.container.pull_image: always

    jhipster-console:
        image: aayushjain/jhipster-console:latest
        environment:
            - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
        ports:
            - "5601:5601"
        depends_on:
            - jhipster-elasticsearch
        labels:
            io.rancher.container.pull_image: always

    jhipster-import-dashboards:
        image: aayushjain/jhipster-import-dashboards:latest
        environment:
            - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
        depends_on:
            - jhipster-elasticsearch
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.start_once: 'true'

    jhipster-alerter:
        image: aayushjain/jhipster-alerter:latest
        # Uncomment this section to enable alerting
        volumes:
            #- jhipster-alerter-config-vol:/opt/elastalert/config.yaml
            #- jhipster-alerter-rule-vol:/opt/elastalert/rules/
            - jhipster-alerter-vol:/opt/elastalert
        labels:
            io.rancher.container.pull_image: always

    jhipster-curator:
        image: aayushjain/jhipster-curator:latest
        environment:
             - ES_HOST=jhipster-elasticsearch
             - UNIT_COUNT=7
             - UNIT=days
        labels:
            io.rancher.container.pull_image: always

    jhipster-zipkin:
        image: aayushjain/jhipster-zipkin:latest
        environment:
            - ES_HOSTS=http://jhipster-elasticsearch:9200
            - ZIPKIN_UI_LOGS_URL=http://jhipster-console:5601/app/kibana#/dashboard/logs-dashboard?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1h,mode:quick,to:now))&_a=(filters:!(),options:(darkTheme:!f),panels:!((col:1,id:logs-levels,panelIndex:2,row:1,size_x:6,size_y:3,type:visualization),(col:7,columns:!(stack_trace),id:Stacktraces,panelIndex:7,row:1,size_x:4,size_y:3,sort:!('@timestamp',desc),type:search),(col:11,id:Log-forwarding-instructions,panelIndex:8,row:1,size_x:2,size_y:3,type:visualization),(col:1,columns:!(app_name,message),id:All-logs,panelIndex:9,row:4,size_x:12,size_y:7,sort:!('@timestamp',asc),type:search)),query:(query_string:(analyze_wildcard:!t,query:'{traceId}')),title:logs-dashboard,uiState:())
        ports:
            - 9411:9411
        labels:
            io.rancher.container.pull_image: always

volumes:
  jhipster-elasticsearch-vol:
    driver: pxd
    external: false
    driver_opts:
       size: 10
       repl: 3
  jhipster-alerter-vol:
    driver: pxd
    external: false
    driver_opts:
       size: 1
       repl: 3